# Generated by Django 4.2.8 on 2023-12-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_rename_image1_pack_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, default='images/pack/default.png', max_length=255, null=True, upload_to='images/pack/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='prerequis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='private_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='public_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pack',
            name='inclus',
            field=models.TextField(default=''),
        ),
    ]
