# Generated by Django 4.2.8 on 2023-12-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0004_categoryoption_option_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoption',
            name='etiquette',
        ),
    ]
