# Generated by Django 4.2.8 on 2023-12-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0005_remove_categoryoption_etiquette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_option', to='HotelApp.categoryoption'),
        ),
    ]
